version: "3.8"
services:
    mysql:
        image: mariadb:10.6
        container_name: climbing-db
        working_dir: /application
        volumes:
            - .:/application
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"